# -*- encoding : utf-8 -*-
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
lugares = []
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Praça do Ciclista', :latitude => '-23.556238', :longitude => '-46.662369')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Pinheiros (CPTM)', :latitude => '-23.566111', :longitude => '-46.705284')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Guilhermina-Esperança (Metrô)', :latitude => '-23.530661', :longitude => '-46.517422')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Senac - Consolação', :latitude => '-23.559109', :longitude => '-46.670952')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Itaú Cultural', :latitude => '-23.570124', :longitude => '-46.646919')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Shopping Frei Caneca', :latitude => '-23.553366', :longitude => '-46.652672')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Pinacoteca do Estado', :latitude => '-23.575630', :longitude => '-46.612930')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Academia Runner - Tatuapé', :latitude => '-23.505442', :longitude => '-46.459808')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Locadora Blockbuster', :latitude => '-23.558952', :longitude => '-46.495171')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Shopping Anália Franco', :latitude => '-23.565247', :longitude => '-46.561260')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Carrefour Aricanduva', :latitude => '-23.561964', :longitude => '-46.517029')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Supermercado Andorinha', :latitude => '-23.470226', :longitude => '-46.649132')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Terminal Pirituba', :latitude => '-23.438679', :longitude => '-46.753006')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Decatlhon - Raposo Tavares', :latitude => '-23.589161', :longitude => '-46.786652')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Decatlhon - Morumbi', :latitude => '-23.612835', :longitude => '-46.702988')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'FNAC Pinheiros', :latitude => '-23.562611', :longitude => '-46.692066')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Locadora Premiere Video', :latitude => '-23.549707', :longitude => '-46.683537')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'SESC Pompéia', :latitude => '-23.525396', :longitude => '-46.682629')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Continental Shopping', :latitude => '-23.547306', :longitude => '-46.747856')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Shopping Eldorado', :latitude => '-23.572287', :longitude => '-46.696789')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Shopping West Plaza', :latitude => '-23.599228', :longitude => '-47.176666')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Pão de Açúcar - Gabriel Monteiro', :latitude => '-23.578934', :longitude => '-46.665974')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Academia Competition', :latitude => '-23.554939', :longitude => '-46.675888')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Academia Competition', :latitude => '-23.568254', :longitude => '-46.642326')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Galeria dos Pães', :latitude => '-23.631472', :longitude => '-46.665802')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Cultura Inglesa - Santo Amaro', :latitude => '-23.601746', :longitude => '-46.587524')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'SESC Ipiranga', :latitude => '-23.606779', :longitude => '-46.582031')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'SESC Vila Mariana', :latitude => '-23.581797', :longitude => '-46.644119')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Shopping Ibirapuera', :latitude => '-23.609808', :longitude => '-46.668056')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Shopping Market Place', :latitude => '-23.621330', :longitude => '-46.698849')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Academia TEM Esportes', :latitude => '-23.669132', :longitude => '-46.566669')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Ginásio Poliesportivo Adyb Moisés Dib', :latitude => '-23.679268', :longitude => '-46.557655')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Locadora Blockbuster - Alphaville', :latitude => '-23.260273', :longitude => '-47.047577')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Academia Mak Fitness', :latitude => '-23.651651', :longitude => '-46.572952')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Parque Municipal Salvador Arena', :latitude => '-23.707094', :longitude => '-46.800385')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Shopping ABC Plaza', :latitude => '-23.649893', :longitude => '-46.532585')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Carrefour - São Bernardo', :latitude => '-23.678171', :longitude => '-46.555939')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Terminal Metropolitano São Bernardo do Campo', :latitude => '-23.709295', :longitude => '-46.554565')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Shopping Flamingo Mall', :latitude => '-23.521181', :longitude => '-46.842957')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Shopping Tamboré', :latitude => '-23.504681', :longitude => '-46.832573')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Mauá (CPTM)', :latitude => '-23.670574', :longitude => '-46.457249')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Pão de Açúcar - Mourato Coelho', :latitude => '-23.564568', :longitude => '-46.686787')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Pão de Açúcar - Av. Ibirapuera', :latitude => '-23.604183', :longitude => '-46.718761')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Shopping Paulista', :latitude => '-23.570930', :longitude => '-46.642262')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Parque da Aclimação', :latitude => '-23.572557', :longitude => '-46.629215')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Autódromo (CPTM)', :latitude => '-23.878304', :longitude => '-46.713867')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Pão de Açúcar - Cardoso de Almeida', :latitude => '-23.535494', :longitude => '-46.666477')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estapar - Conjunto Nacional', :latitude => '-23.559345', :longitude => '-46.659664')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estapar - Joaquim Floriano', :latitude => '-23.630056', :longitude => '-46.681080')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estapar - Pedroso Alvarenga', :latitude => '-23.413477', :longitude => '-46.748199')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estapar - Nações Unidas', :latitude => '-23.767752', :longitude => '-46.862183')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estapar - Moema', :latitude => '-23.622665', :longitude => '-46.695671')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estapar - Nestor Pestana', :latitude => '-23.548801', :longitude => '-46.645458')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estapar - República I', :latitude => '-23.539516', :longitude => '-46.642498')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estapar - Brig. Luís Antônio', :latitude => '-23.552855', :longitude => '-46.637905')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estapar - Perdizes', :latitude => '-23.396463', :longitude => '-46.596451')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Shopping Metrô Santa Cruz', :latitude => '-23.598663', :longitude => '-46.636745')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Lojas Americanas (Blockbuster)  - Tucuruvi', :latitude => '-24.036430', :longitude => '-46.713867')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Terminal Ana Neri (Expresso Tiradentes)', :latitude => '-23.363058', :longitude => '-46.590271')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Biblioteca Monteiro Lobato / Praça Rotary', :latitude => '-23.544937', :longitude => '-46.649590')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Parque da Luz', :latitude => '-23.531570', :longitude => '-46.634731')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => '2001 vídeo locadora - Av. Sumaré', :latitude => '-23.543482', :longitude => '-46.676765')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Frutaria São Paulo', :latitude => '-23.597467', :longitude => '-46.667126')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Novotel Jaraguá', :latitude => '-23.548368', :longitude => '-46.643356')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Centro Cultural São Paulo', :latitude => '-23.570280', :longitude => '-46.639709')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Shopping Iguatemi', :latitude => '-23.576141', :longitude => '-46.687710')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Jurubatuba (CPTM)', :latitude => '-23.678642', :longitude => '-46.700306')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'McDonalds Tremembé', :latitude => '-23.458384', :longitude => '-46.614796')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Caieiras (CPTM)', :latitude => '-23.365589', :longitude => '-46.751289')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Horto Florestal', :latitude => '-23.459242', :longitude => '-46.633659')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Campus Senac', :latitude => '-23.670086', :longitude => '-46.700958')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Pão de Açucar', :latitude => '-23.581688', :longitude => '-46.639538')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Square Academia', :latitude => '-23.666449', :longitude => '-46.561325')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Clínica psicológica Sandra Martino', :latitude => '-23.660721', :longitude => '-46.564522')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Terminal Metrô Pedro II (Expresso Tiradentes)', :latitude => '-23.551004', :longitude => '-46.626835')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Parque Tenente Siqueira Campos (Parque Trianon) ', :latitude => '-23.561666', :longitude => '-46.657219')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Shopping Morumbi', :latitude => '-23.616373', :longitude => '-46.693611')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Garagem São Luís', :latitude => '-23.556513', :longitude => '-46.661316')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Hospital Santa Catarina ', :latitude => '-23.570084', :longitude => '-46.645695')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estapar - Top Center Joaquim Eugênio', :latitude => '-23.565639', :longitude => '-46.650223')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Corinthians-Itaquera (Metrô)', :latitude => '-23.535032', :longitude => '-46.461868')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Carrão (Metrô)', :latitude => '-23.538179', :longitude => '-46.564350')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Sé (Metrô)', :latitude => '-23.551123', :longitude => '-46.632629')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Bicicletário Municipal de Santo André', :latitude => '-23.654991', :longitude => '-46.529568')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Comendador Ermelino (CPTM)', :latitude => '-23.491745', :longitude => '-46.452984')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Itaim Paulista (CPTM)', :latitude => '-23.494225', :longitude => '-46.402775')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Jardim Helena-Vila Mara (CPTM)', :latitude => '-23.493683', :longitude => '-46.410744')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Jardim Romano (CPTM)', :latitude => '-23.486097', :longitude => '-46.387966')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Itapevi (CPTM)', :latitude => '-23.546047', :longitude => '-46.935097')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Artur Alvim (Metrô)', :latitude => '-23.589514', :longitude => '-46.601173')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Vila Matilde (Metrô)', :latitude => '-23.531923', :longitude => '-46.530663')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Penha (Metrô)', :latitude => '-23.533300', :longitude => '-46.545982')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Belém (Metrô)', :latitude => '-23.544476', :longitude => '-46.588211')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Vila das Belezas (Metrô)', :latitude => '-23.640436', :longitude => '-46.745968')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Campo Limpo (Metrô)', :latitude => '-23.649595', :longitude => '-46.759228')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Capão Redondo (Metrô)', :latitude => '-23.531689', :longitude => '-46.502167')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Paraíso (Metrô)', :latitude => '-23.576101', :longitude => '-46.641556')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Vila Mariana (Metrô)', :latitude => '-23.667795', :longitude => '-46.648636')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Marechal Deodoro (Metrô)', :latitude => '-23.534245', :longitude => '-46.656147')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Anhangabaú (Metrô)', :latitude => '-23.553917', :longitude => '-46.630783')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Liberdade (Metrô)', :latitude => '-23.586643', :longitude => '-46.882782')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação São Bento (Metrô)', :latitude => '-23.545025', :longitude => '-46.634731')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Tiradentes (Metrô)', :latitude => '-23.544788', :longitude => '-46.577568')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Palmeiras-Barra Funda (Metrô)', :latitude => '-23.526258', :longitude => '-46.666744')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Santa Cecília (Metrô)', :latitude => '-23.495838', :longitude => '-46.609669')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Brás (Metrô)', :latitude => '-23.539675', :longitude => '-46.614475')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Terminal Mercado (Expresso Tiradentes)', :latitude => '-23.538494', :longitude => '-46.642971')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Terminal Rua do Grito (Expresso Tiradentes)', :latitude => '-23.598215', :longitude => '-46.597244')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Terminal Sacomã (Expresso Tiradentes)', :latitude => '-23.625652', :longitude => '-46.656189')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Terminal C. A. Ypiranga (Expresso Tiradentes)', :latitude => '-23.573742', :longitude => '-46.602631')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'G3 Esportes', :latitude => '-23.407806', :longitude => '-46.506500')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Farmácia', :latitude => '-23.621878', :longitude => '-46.674728')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Terminal Nossa Senhora Aparecida (Expresso Tiradentes)', :latitude => '-23.529997', :longitude => '-46.619110')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Espaço Verde Chico Mendes', :latitude => '-23.631718', :longitude => '-46.571999')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Parada do Ciclista', :latitude => '-23.609690', :longitude => '-46.576538')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Parque da Independência', :latitude => '-23.594194', :longitude => '-46.584263')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Central Plaza Shopping', :latitude => '-23.597397', :longitude => '-46.581142')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Shopping Higienópolis', :latitude => '-23.542665', :longitude => '-46.657734')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Vila Madalena (Metrô)', :latitude => '-23.551085', :longitude => '-46.690350')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Armênia (Metrô)', :latitude => '-23.526770', :longitude => '-46.629280')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Santana (Metrô)', :latitude => '-23.482693', :longitude => '-46.631386')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Shopping Bourbon', :latitude => '-23.526258', :longitude => '-46.681122')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Decathlon', :latitude => '-23.516262', :longitude => '-46.614044')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Bicicletários Porto Seguro – Matriz', :latitude => '-23.468285', :longitude => '-46.668549')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Academia Bio Ritmo', :latitude => '-23.558716', :longitude => '-46.660397')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Shopping Jardim Sul', :latitude => '-23.630371', :longitude => '-46.736526')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'USP: Instituto de Física', :latitude => '-23.559883', :longitude => '-46.734730')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'USP: Instituto Astronômico e Geofísico', :latitude => '-23.736956', :longitude => '-46.781845')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Instituto de Química - USP', :latitude => '-23.566032', :longitude => '-46.726357')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Universidade São Paulo Faculdade de Educação', :latitude => '-23.561922', :longitude => '-46.717342')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'CRUSP-USP', :latitude => '-23.558479', :longitude => '-46.720711')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Terminal Sapopemba', :latitude => '-23.630686', :longitude => '-46.500320')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'D&#39;Avó Supermercados Ltda', :latitude => '-23.498163', :longitude => '-46.455521')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'CPTM-Companhia Paulista de Trens Metropolitanos', :latitude => '-23.491119', :longitude => '-46.440083')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estádio Paulo Machado de Carvalho - Pacaembu', :latitude => '-23.514099', :longitude => '-46.665287')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Lojas Americanas (Blockbuster)', :latitude => '-23.482077', :longitude => '-46.631138')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Vila Olímpia (CPTM)', :latitude => '-23.593094', :longitude => '-46.692841')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Bicicletário FEA', :latitude => '-23.558046', :longitude => '-46.728073')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Bicicletário Mackenzie', :latitude => '-23.548016', :longitude => '-46.652626')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Lanchonete', :latitude => '-23.598127', :longitude => '-46.664944')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Santana Parque Shopping', :latitude => '-23.482752', :longitude => '-46.645119')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Parque do Trote', :latitude => '-23.514887', :longitude => '-46.597599')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Geografia / História - FFLCH-USP', :latitude => '-23.563480', :longitude => '-46.722900')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'CEPE-USP', :latitude => '-23.561411', :longitude => '-46.717323')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Poli-USP', :latitude => '-23.545420', :longitude => '-46.731720')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Alameda dos bancos - USP', :latitude => '-23.578148', :longitude => '-46.726227')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Instituto Geociências - USP', :latitude => '-23.562237', :longitude => '-46.727524')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Museu de Arte Moderna (mam)', :latitude => '-23.587036', :longitude => '-46.655586')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Supermercado Extra Freguesia', :latitude => '-23.505314', :longitude => '-46.689674')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Terminal Vila Nova Cachoeirinha', :latitude => '-23.474779', :longitude => '-46.669815')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Bergamais Supermercado', :latitude => '-23.477610', :longitude => '-46.645252')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Shopping Center Norte', :latitude => '-23.545261', :longitude => '-46.623058')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'R. Machado Bitencourt, 300 - Saúde', :latitude => '-23.600075', :longitude => '-46.638359')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'FESPSP - Fundação Escola de Sociologia e Política de São Paulo', :latitude => '-23.544445', :longitude => '-46.649677')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Goa', :latitude => '-23.557182', :longitude => '-46.687088')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Bicicletário - Metro Jabaquara / EMTU', :latitude => '-23.646528', :longitude => '-46.640331')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Tutto Bike', :latitude => '-23.531599', :longitude => '-46.685703')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Pão-de-Açúcar Planalto Paulista', :latitude => '-23.623608', :longitude => '-46.659279')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Cidade Universitária - Butantã', :latitude => '-23.566425', :longitude => '-46.730846')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Daslu - Loja de roupas', :latitude => '-23.583969', :longitude => '-46.662884')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Sesc Ipiranga', :latitude => '-23.582130', :longitude => '-46.607929')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Supermercado Sonda', :latitude => '-23.495996', :longitude => '-46.744595')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Pista de skate do Sumaré', :latitude => '-23.550699', :longitude => '-46.677593')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Entrada da ciclovia na Marginal', :latitude => '-23.606817', :longitude => '-46.674042')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Entrada para Ciclovia da Marginal', :latitude => '-23.694206', :longitude => '-46.524353')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Parque Municipal Mario Covas', :latitude => '-23.560053', :longitude => '-46.658314')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Americanas Blockbusters Express', :latitude => '-23.540842', :longitude => '-46.676121')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Mercado de Peixe', :latitude => '-23.986044', :longitude => '-46.294922')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'CUIDADO PERIGO', :latitude => '-23.935989', :longitude => '-46.332558')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Travessia de Balsa Guarujá - Santos', :latitude => '-23.987392', :longitude => '-46.294617')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estacionamento do Parque Antartica', :latitude => '-23.526560', :longitude => '-46.677761')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'McDonalds', :latitude => '-23.563421', :longitude => '-46.678116')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Parque das Bicicletas', :latitude => '-23.600262', :longitude => '-46.657497')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Cidade Universitária (CPTM)', :latitude => '-23.557220', :longitude => '-46.711357')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Sesc Pinheiros', :latitude => '-23.567739', :longitude => '-46.697403')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Shopping SP Market', :latitude => '-23.676619', :longitude => '-46.699081')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Poupatempo Sé', :latitude => '-23.551001', :longitude => '-46.630836')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Sacolão na Vila Madalena', :latitude => '-23.554756', :longitude => '-46.685619')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Instituto Tomie Othake', :latitude => '-23.561104', :longitude => '-46.694092')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'De: Rua Maracá, 115, Jabaquara, São Paulo, Brasil', :latitude => '-23.633923', :longitude => '-46.637787')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Para: R das Pitangueiras 470 Bairro Jardim', :latitude => '-23.649698', :longitude => '-46.540371')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => '-25.391233, -49.266766', :latitude => '-25.391233', :longitude => '-49.266766')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Galeria Cine Gemini', :latitude => '-23.566465', :longitude => '-46.651062')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Supermercado Extra', :latitude => '-23.566042', :longitude => '-46.647755')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Habib&#39;s Tremembé', :latitude => '-23.457726', :longitude => '-46.616665')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Pão de Açúcar - Primeiro de Janeiro', :latitude => '-23.602158', :longitude => '-46.639767')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'R. Novo Cancioneiro, 65 - Itaim Bibi', :latitude => '-23.623861', :longitude => '-46.689884')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'De: R. Dr. Timóteo Penteado - Guarulhos - São Paulo', :latitude => '-23.451860', :longitude => '-46.551891')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Para: SHOPPING BONSUCESSO - Avenida Juscelino Kubitschek de Oliveira,, 5308 - Guarulhos', :latitude => '-23.431299', :longitude => '-46.405659')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Palermo', :latitude => '38.115620', :longitude => '13.361376')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'CCJ - Centro Cultural da Juventude', :latitude => '-23.476030', :longitude => '-46.670319')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Paraciclos', :latitude => '-23.564302', :longitude => '-46.502747')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'R. Gonçalo Afonso, 99 - Pinheiros', :latitude => '-23.556585', :longitude => '-46.686310')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'De: Rua Buenos Aires, Rio de Janeiro, Brasil', :latitude => '-22.903851', :longitude => '-43.181492')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Para: Rua Guapeni, 34, Rio de Janeiro, Brasil', :latitude => '-22.924290', :longitude => '-43.229572')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Bicicletaria', :latitude => '-23.567762', :longitude => '-46.621460')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Pão-de-Açúcar', :latitude => '-23.616098', :longitude => '-46.739487')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'R. Felipe Angeli, 2 - Iguatemi', :latitude => '-23.598888', :longitude => '-46.421185')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Parque da Independência - Inferior', :latitude => '-23.579800', :longitude => '-46.610279')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Parque da Independência - Superior', :latitude => '-23.585335', :longitude => '-46.609680')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'R. Lambda - Caiçaras', :latitude => '-19.894266', :longitude => '-43.966618')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'De: R. pedro luís de souza- São Paulo', :latitude => '-23.558969', :longitude => '-46.492722')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Para: R. Frei Francisco - José Bonifácio, São Paulo - São Paulo, 08420-200', :latitude => '-23.539110', :longitude => '-46.428829')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Av. das Cerejeiras, 2122 - Vila Maria', :latitude => '-23.502777', :longitude => '-46.574043')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Shoppping Butantã', :latitude => '-23.586094', :longitude => '-46.724876')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'R. Camargo, 291-457 - Butantã', :latitude => '-23.570797', :longitude => '-46.709145')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Sala São Paulo', :latitude => '-23.534229', :longitude => '-46.640354')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Av. Brg. Luís Antônio, 5013 - Itaim Bibi', :latitude => '-23.583769', :longitude => '-46.669666')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Marcador de lugar 173', :latitude => '-23.537268', :longitude => '-46.641350')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Bicicletário PUC', :latitude => '-23.537830', :longitude => '-46.671730')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'De: Rua Violeta, Belo Horizonte - Minas Gerais', :latitude => '-19.906919', :longitude => '-43.904789')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Para: Três Marias - Minas Gerais', :latitude => '-18.204702', :longitude => '-45.232727')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Fundação Sos Mata Atlantica', :latitude => '-23.571283', :longitude => '-46.651112')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'R. Dr. Albuquerque Lins, 94 - Santa Cecília', :latitude => '-23.523701', :longitude => '-46.669922')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'R. Dr. Albuquerque Lins, 94 - Santa Cecília', :latitude => '-23.523701', :longitude => '-46.669922')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'R. Jumana, 56 - Móoca', :latitude => '-23.566313', :longitude => '-46.598873')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Kolpos Irakleiou', :latitude => '35.355301', :longitude => '25.082184')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'R. Stella Hanriot, 420 - Buritis', :latitude => '-19.971552', :longitude => '-43.969341')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Travessia balsa', :latitude => '-23.989231', :longitude => '-46.290634')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'cuidado', :latitude => '-23.986414', :longitude => '-46.295128')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Big Small', :latitude => '-23.564415', :longitude => '-46.684898')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Stiltecentrum Hoog Catharijne', :latitude => '52.090340', :longitude => '5.112634')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Marcador de lugar 173', :latitude => '-23.559258', :longitude => '-46.689060')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Pão de Açúcar - Gabriel Monteiro', :latitude => '-23.571459', :longitude => '-46.681091')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Faculdade Italo Brasileira Teatro Paulo Autran', :latitude => '-23.608412', :longitude => '-46.660896')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'De: Rua Botucatu, 469, São Paulo', :latitude => '-23.595922', :longitude => '-46.642399')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Para: R. Maria de Castro Mesquita, 148 - Centro, Guarulhos - São Paulo, 07110-040', :latitude => '-23.465506', :longitude => '-46.527718')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'From: Av. Jorn. Roberto Marinho/Av. Água Espraiada', :latitude => '-23.637529', :longitude => '-46.662849')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'R. Rio Moxotó, 28-78 - Ibura', :latitude => '-8.116702', :longitude => '-34.930355')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Av. Ibirapuera, 2033 - Moema', :latitude => '-23.600960', :longitude => '-46.661510')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Metrô Capão Redondo', :latitude => '-23.659107', :longitude => '-46.768456')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Sun Harbour Boutique Hotel Llc', :latitude => '25.886812', :longitude => '-80.122772')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Vila Olimpia', :latitude => '-23.593060', :longitude => '-46.692879')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Bicicletário Câmara Municipal', :latitude => '-23.550751', :longitude => '-46.641178')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Paraciclo Biblioteca Mario de Andrade', :latitude => '-23.547670', :longitude => '-46.641575')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'UseBike Novotel Ibirapuera', :latitude => '-23.591991', :longitude => '-46.648891')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Metrô Butantã', :latitude => '-23.571535', :longitude => '-46.708801')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'CCJ- Centro Cultural', :latitude => '-23.475883', :longitude => '-46.670189')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Senac Santana', :latitude => '-23.491823', :longitude => '-46.626213')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Senac Scipião', :latitude => '-23.521919', :longitude => '-46.698879')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Marcador de lugar 3', :latitude => '-23.514336', :longitude => '-46.629368')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Marcador de lugar 4', :latitude => '-23.514336', :longitude => '-46.629368')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Marcador de lugar 5', :latitude => '-23.514336', :longitude => '-46.629368')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Marcador de lugar 6', :latitude => '-23.514336', :longitude => '-46.629368')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Marcador de lugar 9', :latitude => '-23.514336', :longitude => '-46.629368')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Marcador de lugar 7', :latitude => '-23.514336', :longitude => '-46.629368')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Marcador de lugar 8', :latitude => '-23.514336', :longitude => '-46.629368')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Marcador de lugar 10', :latitude => '-23.514336', :longitude => '-46.629368')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estacionamento no Museu Casa Brasi', :latitude => '-23.579849', :longitude => '-46.684814')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Casa Jaya', :latitude => '-23.558800', :longitude => '-46.674843')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Bicicletário no Shopping Butantã ã', :latitude => '-23.584913', :longitude => '-46.724831')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Pastificio Primo', :latitude => '-23.547289', :longitude => '-46.655544')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Sem ciclovia', :latitude => '-23.578384', :longitude => '-46.708889')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'bicicletário da câmara Municipal', :latitude => '-23.550699', :longitude => '-46.641159')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Shopping Vila Olimpia', :latitude => '-23.595364', :longitude => '-46.687840')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => '種子島中学校', :latitude => '30.737223', :longitude => '130.998184')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'De: R. Açucena, 110 - Km 18, Osasco - São Paulo, BRA', :latitude => '-23.533535', :longitude => '-46.788570')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Para: R. José Joaquim Pinto - Osasco - São Paulo, 06120-210, Brasil', :latitude => '-23.544621', :longitude => '-46.790798')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Rod. Pres. Castelo Branco', :latitude => '-23.506453', :longitude => '-46.843922')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'De: R. João Ruthner, 141 - Moinhos, Lajeado - Rio Grande do Sul, 95900-000', :latitude => '-29.464308', :longitude => '-51.974388')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Para: Venâncio Aires - RS', :latitude => '-29.606037', :longitude => '-52.194401')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => '3 Porter St', :latitude => '37.734718', :longitude => '-122.418083')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Padaria Villa Real', :latitude => '-23.523190', :longitude => '-46.687073')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Av. das Nações Unidas, 20882 - Campo Grande', :latitude => '-23.665594', :longitude => '-46.708054')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'R. Dr. Aniceto Ribeiro Varejão, 123 - Torrões', :latitude => '-8.066347', :longitude => '-34.932495')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Marcador de lugar 171', :latitude => '-23.547956', :longitude => '-46.639343')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Bicicletário Metrô Anhangabaú', :latitude => '-23.547701', :longitude => '-46.639645')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Anhangabaú', :latitude => '-23.547760', :longitude => '-46.639668')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Via perigosa', :latitude => '-23.618692', :longitude => '-46.758286')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => '-23.560289, -46.664386', :latitude => '-23.560289', :longitude => '-46.664387')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => '-23.560289, -46.664386', :latitude => '-23.560289', :longitude => '-46.664387')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Marcador de lugar 171', :latitude => '-23.503592', :longitude => '-46.548344')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Marcador de lugar 171', :latitude => '-23.432064', :longitude => '-46.595421')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Bicicletário Shopping Penha', :latitude => '-23.525097', :longitude => '-46.546284')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Estação Primavera-Interlagos', :latitude => '-23.721947', :longitude => '-46.691765')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => '(Start)', :latitude => '-23.695059', :longitude => '-46.684540')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => '(End)', :latitude => '-23.594177', :longitude => '-46.693134')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'De: R. Eng. Francisco Pitta Brito, 703 - Santo Amaro, São Paulo - São Paulo', :latitude => '-23.657606', :longitude => '-46.714272')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Para: av dr cardoso de melo', :latitude => '-23.599001', :longitude => '-46.683510')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Para: Av. Divino Salvador, 58 - Moema, São Paulo - São Paulo', :latitude => '-23.604244', :longitude => '-46.660606')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Av. Armando de Andrade, 313 - Jardim Alvorada', :latitude => '-23.607206', :longitude => '-46.755642')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Águas de Lindóia - São Paulo', :latitude => '-22.475449', :longitude => '-46.633518')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Pão de Açúcar', :latitude => '-23.458050', :longitude => '-46.617565')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Museu Lazar Segall', :latitude => '-23.594765', :longitude => '-46.635323')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Casa das Rosas', :latitude => '-23.570782', :longitude => '-46.645256')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Museu Lasar Segall', :latitude => '-23.594765', :longitude => '-46.635269')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Metrô Vila Mariana', :latitude => '-23.589594', :longitude => '-46.635033')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Casa na Praia - bar/rest', :latitude => '-23.584015', :longitude => '-46.648014')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Travessa Dr. José Alves de Sousa Neto - Itaim Bibi', :latitude => '-23.594503', :longitude => '-46.685921')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Travessa Dr. José Alves de Sousa Neto - Itaim Bibi', :latitude => '-23.594503', :longitude => '-46.685921')
lugares << Lugar.new(:executa_geolocalizacao_reversa => true, :tipo => 'importado', :nome => 'Palmeira - PR', :latitude => '-25.434237', :longitude => '-49.999928')

lugares.each do |l|
  while l.save == false
    puts "deve tentar novamente - #{l.nome}"
    sleep(200)
  end
end